shiro bjarne stroustrup 4th edition
cat-milk/Anime-Girls-Holding-Programming-Books pull request #216
Opened 2021-07-05 21:22 UTC by bfu4

2021-07-06 00:31 UTC, ven commented
lgtm

2021-07-20 06:14 UTC, Looskie commented
LGTM

2021-07-20 06:15 UTC, Looskie requested changes
LBTM!

2021-07-20 06:15 UTC, Looskie commented
yo

2021-07-20 06:15 UTC, Looskie commented
typo

2021-10-15 19:10 UTC, merged

2021-10-16 11:17 UTC, Looskie commented
![image](https://user-images.githubusercontent.com/50378828/137585299-74c31f2d-d8ee-49af-a930-3d0394cf82b4.png)
<h3>thanks for merge</h3>