Added Power Holding Sams Teach Yourself C++
cat-milk/Anime-Girls-Holding-Programming-Books pull request #641
Opened 2023-12-18 19:51 UTC by TahmidRaven

I've added a new image in C++ dir. It's power from chainsaw man. I've only edited the image. Let me know if there's any issue with it.

2024-01-07 19:43 UTC, cat-milk requested changes
This image is fine but the filename needs the spaces in it replace with underscores. Could you make that change so I can merge this?

2024-01-23 18:25 UTC, TahmidRaven commented
Renamed the file as requested. Lemme know if there's anymore issues needed to be resolved. Working on another picture. will add soon.

2024-02-02 09:23 UTC, TahmidRaven commented
```issue resolved; take a look. ``` @cat-milk

2024-03-18 18:04 UTC, Caslus approved these changes

2024-03-23 19:08 UTC, merged